version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: ts-orm-benchmark-db
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres-volume:
    driver: local
